client/app/(servers)/servers/[id]/components/sections/RightSide/Actions.jsx
client/lib/request/servers/createReminder.js
client/lib/request/servers/voteServer.js
server/src/bot/commands/vote.js
server/src/routes/servers/[id]/index.js
server/src/routes/servers/[id]/reminder.js
server/src/routes/servers/[id]/vote.js

This pull request adds several features and enhancements related to reminders and voting functionality in the application. It includes adding a new button to server pages for creating reminder after voting in 10 minutes.
- Added check for user in guild after voting and return it in response.
- Added set reminder route for servers.
- Renamed Reminder to VoteReminder, removed date field from newReminder object.
- Added can_set_reminder field to get server route.
- Removed date field from new vote reminder object.
- Refactored voteServer to return response data.
- Added createReminder function.
- Added create reminder button and functionality to Actions component.
N/A
N/A

Able to create reminder on web

---

client/app/(profiles)/profile/[slug]/content.js
client/app/(profiles)/profile/u/[user_id]/content.js
client/app/(profiles)/profiles/components/Hero/Profiles/Card.jsx
client/locales/az.json
client/locales/en.json
client/locales/tr.json
server/src/bot/commands/general/info.js
server/src/routes/users/[id]/index.js
server/src/utils/profiles/getBadges.js

The tooltips for profile badges used to use the default language's tooltip text, even if the language was changed.
[Refactor getBadges function to use badge IDs instead of names](https://github.com/discordplace/discord.place/commit/7d4d57de263814071a595600a6c5a75bc5c8c341)
[Use badge ids to get emojis in user info command](https://github.com/discordplace/discord.place/commit/c83cf7747d2d30bacea5ea2d61f12be29223d2ed)
[Refactor getBadges function to return badge IDs instead of objects](https://github.com/discordplace/discord.place/commit/b17804df66413ee03b6dba02c5b03a77d73a223f)
[Refactor getBadges function to remove unused comments](https://github.com/discordplace/discord.place/commit/0c38dfa31ce3c923bbd13e342634668ddf9f9eab)
[Update user profile response to include subscription creation …

Fix badges localization

---

client/app/(profiles)/profile/[slug]/content.js

The graphs on the profile page were visible even without data.
[Refactor Profile Slug Content component to conditionally render the G…](https://github.com/discordplace/discord.place/commit/0005445aea555f083d15913b1429d3900a0eb6bb)
N/A

Fix graphs displayed with zero data

---

client/locales/en.json

1. en-US Int'l paradigm specification suggests that titles that include position specifiers should not be capitalized
2. Swapped `About Theme` to `About This Theme` to better follow the en-us Int'l paradigm specification for naming

update english locale to follow en-US Int'l writing rules

---

client/app/(dashboard)/components/Table/index.jsx

This pull request includes a small change to the `Table` component in the `client/app/(dashboard)/components/Table/index.jsx` file. The change adjusts the styling of the span element that displays the tab count.
Styling adjustment:
* [`client/app/(dashboard)/components/Table/index.jsx`](diffhunk://#diff-27ea240cc4fb536fe8eaaf1930dc6ac385501579211971a3181ced9f71a962a5L112-R112): Changed the span element's class to use `w-max` and `px-1.5` for better styling and alignment of the tab count.

Fix tab count display

---

server/package.json
server/pnpm-lock.yaml
server/src/routes/index.js
server/src/server.js

This pull request introduces Swagger documentation to the server, updates dependencies, and adds new packages in the `pnpm-lock.yaml` file. The most important changes include adding Swagger setup in the server, updating the `package.json` to include new dependencies.
* Added Swagger setup in `server.js` to generate API documentation. (`server/src/server.js`) [[1]](diffhunk://#diff-1ce490ef081c1064c1bcc2dfdd71617a390b3b9624b48a0e3935b23e6698edfbL3-R5) [[2]](diffhunk://#diff-1ce490ef081c1064c1bcc2dfdd71617a390b3b9624b48a0e3935b23e6698edfbR37) [[3]](diffhunk://#diff-1ce490ef081c1064c1bcc2dfdd71617a390b3b9624b48a0e3935b23e6698edfbR95-R122)
* Added Swagger documentation for the root endpoint in `index.js`. (`server/src/routes/index.js`)
* Added `swagger-jsdoc` to `package.json`. …

Add Swagger integration

---

server/src/client.js

This pull request to `server/src/client.js` includes changes to remove the `axios` dependency and the `getResponseTime` method. These changes help to simplify the codebase by eliminating unused code and dependencies.
Codebase simplification:
* [`server/src/client.js`](diffhunk://#diff-f6861b176e4409c57d839b2b126db6b1a1cbec4962008a942a4fdb275ba35a45L4): Removed the `axios` dependency as it is no longer needed.
* [`server/src/client.js`](diffhunk://#diff-f6861b176e4409c57d839b2b126db6b1a1cbec4962008a942a4fdb275ba35a45L339-L352): Removed the `getResponseTime` method from the `Client` class, which included `axios` calls to fetch response time data.

Remove unused getResponseTime function

---

client/app/components/Markdown/index.jsx

This pull request includes a small but important change to the `Markdown` component in the `client/app/components/Markdown/index.jsx` file. The change ensures that long words within the markdown content will break correctly, improving the readability and layout of the rendered markdown.
* [`client/app/components/Markdown/index.jsx`](diffhunk://#diff-d0da64a23e30c0eeab1dc57a8cf112005290b02eb2be99239d4e51ba10781999L13-R13): Added the `break-words` class to the `Markdown` component to ensure long words break correctly.

fix(client/markdown): allow line breaks in rendered markdown content

---

client/app/components/Pagination/index.jsx

This pull request includes a small change to the `Pagination` component in `client/app/components/Pagination/index.jsx`. The change ensures that the page input field is properly handled when it loses focus (`onBlur` event).
* [`client/app/components/Pagination/index.jsx`](diffhunk://#diff-236d1d8fa246da7278789a2c79d724f1f46a9b228ed5f9f13f708861c7a9e7a8R128-R131): Added an `onBlur` event handler to close the input field and set the page number within valid bounds when the input field loses focus.

fix(pagination): close input on blur and update page number

---

client/app/premium/content.jsx

This pull request includes a small change to the `client/app/premium/content.jsx` file. The change involves removing unnecessary placeholder code.
* [`client/app/premium/content.jsx`](diffhunk://#diff-430ac1528d67e8e0d6d8e06f45a35e05fe27de5f00cdf16c1e4685c372f14282L221-L226): Removed a nested `div` containing placeholder text "asd" to clean up the component.

refactor(content): remove unnecessary nested divs from premium page

---

client/app/premium/content.jsx

This pull request to `client/app/premium/content.jsx` includes changes to improve the user interface by replacing an icon and restructuring the tooltip for feature information. The most important changes include replacing the `BiSolidInfoCircle` icon with a tooltip and restructuring the `h2` element to include the tooltip directly.
Improvements to the user interface:
* [`client/app/premium/content.jsx`](diffhunk://#diff-430ac1528d67e8e0d6d8e06f45a35e05fe27de5f00cdf16c1e4685c372f14282L21): Removed the import for `BiSolidInfoCircle`.
* [`client/app/premium/content.jsx`](diffhunk://#diff-430ac1528d67e8e0d6d8e06f45a35e05fe27de5f00cdf16c1e4685c372f14282L328-R333): Restructured the `h2` element to include the tooltip directly, improving the user experience by making the feature information more …

feat: redesign Tooltip usage in premium page

---

client/app/(account)/account/components/Content/Tabs/ActiveReminders/index.jsx
client/locales/az.json
client/locales/en.json
client/locales/tr.json

This pull request includes several changes to the `ActiveReminders` component and updates to localization files. The main changes improve the user interface and add new translations for reminder titles.
* Added new imports for `IoChevronDown`, `IoPaperPlane`, `AnimateHeight`, and `useState` to enhance the UI and manage state. (`client/app/(account)/account/components/Content/Tabs/ActiveReminders/index.jsx`)
* Introduced a new state variable `activeReminder` to track the currently active reminder. (`client/app/(account)/account/components/Content/Tabs/ActiveReminders/index.jsx`)
* Updated the reminders list to sort by creation date and added click functionality to toggle the active reminder. (`client/app/(account)/account/components/Content/Tabs/ActiveReminders/index.jsx`)
* Enhanced the …

feat: redesign Active Reminders page with expandable details

---

client/lib/getHashFromURL.js

This pull request includes a small but important change to the `client/lib/getHashFromURL.js` file. The change modifies the `getHashFromURL` function to correctly parse the hash from the URL.
* [`client/lib/getHashFromURL.js`](diffhunk://#diff-f9634621efd0d9410262fb8674897b7177a699ef2ef58f3dffd75b8af89702dfL4-R4): Updated the `getHashFromURL` function to correctly handle URLs by splitting the string in a more precise manner.

fix: correct hash extraction logic in getHashFromURL function

---

client/app/(account)/account/components/Content/Tabs/ActiveReminders/index.jsx

This pull request includes a small but important change to the `ActiveReminders` component in the `client/app/(account)/account/components/Content/Tabs/ActiveReminders/index.jsx` file. The change adjusts the maximum width of the reminder text to improve the layout and readability on different screen sizes.
* [`client/app/(account)/account/components/Content/Tabs/ActiveReminders/index.jsx`](diffhunk://#diff-7b71f7055ebcedfc2bdaeab56a80d0bf55d915ae045ff4bcdb6839fb7686c678L102-R102): Modified the `max-w` class to use a percentage-based width with an additional `xl:max-w` class for larger screens.

fix: adjust max-width for reminder text in ActiveReminders component

---

client/app/(profiles)/profile/u/[user_id]/content.js

This pull request includes a small change to the `client/app/(profiles)/profile/u/[user_id]/content.js` file. The change updates the code to use `user.avatar_url` instead of `user.avatar` and modifies the `hash` property to use a function `getHashFromURL`.
* `client/app/(profiles)/profile/u/[user_id]/content.js`: Updated to use `user.avatar_url` instead of `user.avatar` and modified the `hash` property to use the `getHashFromURL` function. ([client/app/(profiles)/profile/u/[user_id]/content.jsL130-R133](diffhunk://#diff-f3d760974473eb7f692ee3dc4c95b030c9248bbcbe6f20b9baa4286d9ea2c8d3L130-R133))

fix: use avatar_url instead of avatar in user profile page

---

client/app/(blogs)/blogs/[id]/components/Header.jsx
client/app/(bots)/bots/[id]/components/Tabs/Reviews.jsx
client/app/(bots)/bots/[id]/manage/components/ExtraOwners/index.jsx
client/app/(dashboard)/components/Table/ColumnRenderer.jsx
client/app/(emojis)/emojis/components/Hero/EmojiCard/Package.jsx
client/app/(emojis)/emojis/components/PackagePreview/index.jsx
client/app/(home)/components/InfoCards/Mock/ReviewCard.jsx
client/app/(profiles)/profile/[slug]/components/sections/Social.jsx
client/app/(profiles)/profile/[slug]/edit/components/Socials.jsx
client/app/(servers)/servers/[id]/components/Tabs/Reviews.jsx
client/app/components/Footer/index.jsx
client/app/components/Header/CollapsedHeader.jsx
client/app/components/Logo/WithText.jsx

This pull request removes the `loading='lazy'` attribute from various image components across multiple files to ensure images load immediately rather than lazily.

refactor: remove loading='lazy' attribute from multiple image components

---

client/app/components/ImageFromHash/UserAvatar.jsx
client/app/components/ImageFromHash/UserBanner.jsx

This pull request includes changes to the `UserAvatar` and `UserBanner` components to improve the handling of default images. The modifications ensure that the components only display the default image when necessary.
Changes to `UserAvatar` component:
* [`client/app/components/ImageFromHash/UserAvatar.jsx`](diffhunk://#diff-a680c69ab51e6a6ac6cf9a8bfb77b3cf8befee1fe2ca3947823feb829cbaee18L12-R12): Updated the initial state of `currentSource` from `defaultAvatarURL` to `null` and modified the conditional rendering to check for both `hash` and `currentSource`. [[1]](diffhunk://#diff-a680c69ab51e6a6ac6cf9a8bfb77b3cf8befee1fe2ca3947823feb829cbaee18L12-R12) [[2]](diffhunk://#diff-a680c69ab51e6a6ac6cf9a8bfb77b3cf8befee1fe2ca3947823feb829cbaee18L84-R84)
Changes to `UserBanner` component:
* …

fix(ImageFromHash): show default avatar while current source loading

---

client/app/(themes)/themes/components/ThemeCard/index.jsx

This pull request makes a small but significant change to the `ThemeCard` component to improve its conditional styling logic.
* [`client/app/(themes)/themes/components/ThemeCard/index.jsx`](diffhunk://#diff-8287d9743da6239c8d5dcf4b3df719b2d3d8106c4e1211f7718fc424fee12dcaL14-R15): Modified the `className` attribute to use a ternary operator for conditional styling, ensuring that the `pointer-events-none` and `select-none` classes are only applied when `id` is not present.

fix(ThemeCard): update class names to fix pointer events handling

---

client/app/(profiles)/profile/u/[user_id]/content.js

This pull request includes a small change to the `client/app/(profiles)/profile/u/[user_id]/content.js` file. The change updates the property name for the user's avatar URL to use camelCase.
* `client/app/(profiles)/profile/u/[user_id]/content.js`: Changed `user.avatar_url` to `user.avatarURL` to follow camelCase naming convention. ([client/app/(profiles)/profile/u/[user_id]/content.jsL130-R133](diffhunk://#diff-f3d760974473eb7f692ee3dc4c95b030c9248bbcbe6f20b9baa4286d9ea2c8d3L130-R133))

fix(UserPage): update avatar URL property to use camelCase

---

client/app/(profiles)/profile/u/[user_id]/content.js

This pull request includes changes to improve the handling of user banner and avatar URLs by specifying the type of asset in the `getHashFromURL` function.
Improvements to URL handling:
* `client/app/(profiles)/profile/u/[user_id]/content.js`: Modified the `getHashFromURL` function calls to include the asset type ('banners' for banner URLs and 'avatars' for avatar URLs) for better URL management. ([client/app/(profiles)/profile/u/[user_id]/content.jsL110-R110](diffhunk://#diff-f3d760974473eb7f692ee3dc4c95b030c9248bbcbe6f20b9baa4286d9ea2c8d3L110-R110), [client/app/(profiles)/profile/u/[user_id]/content.jsL133-R133](diffhunk://#diff-f3d760974473eb7f692ee3dc4c95b030c9248bbcbe6f20b9baa4286d9ea2c8d3L133-R133))

fix(UserProfile): add missing parameters to getHashFromURL function calls

---

server/src/server.js

This pull request includes a small change to the `server/src/server.js` file. The change adds an error logging statement when there is an error verifying the token, improving the debugging process.
* [`server/src/server.js`](diffhunk://#diff-1ce490ef081c1064c1bcc2dfdd71617a390b3b9624b48a0e3935b23e6698edfbR125): Added an error logging statement in the token verification error handling block.

fix(Authentication): log error when token verification fails

---

client/app/(account)/account/components/Content/index.jsx
client/app/(dashboard)/components/Sidebar/index.jsx
client/app/components/Header/UserSide.jsx
server/src/server.js

This pull request includes changes to the client to improve the handling of user authentication tokens, specifically focusing on the use of cookies for token management. The most important changes include adding the `useCookie` hook to various components and ensuring that the token is deleted upon user logout.
Client-side updates:
* [`client/app/(account)/account/components/Content/index.jsx`](diffhunk://#diff-df9a9b2bb777468ce3ff9d2cac5174f9c53cf41feebd5317c0e4ddf5ac05bb80L26-R26): Added `useCookie` hook for token management and updated the `logOut` function to delete the token upon logout. [[1]](diffhunk://#diff-df9a9b2bb777468ce3ff9d2cac5174f9c53cf41feebd5317c0e4ddf5ac05bb80L26-R26) [[2]](diffhunk://#diff-df9a9b2bb777468ce3ff9d2cac5174f9c53cf41feebd5317c0e4ddf5ac05bb80R57-R65)
* …

fix(Authentication): delete token cookie on logout

---

client/app/(bots)/bots/components/Hero/SearchResults/Card/index.jsx
client/app/(servers)/servers/components/Hero/index.jsx
client/app/(servers)/servers/components/ServerCard/index.jsx
client/locales/az.json
client/locales/en.json
client/locales/tr.json
server/src/routes/bots/search.js
server/src/routes/servers/search.js

This pull request introduces a new "Most Voted" badge feature for bots and servers, updates the corresponding UI components, and adds localization strings for multiple languages. Additionally, it modifies the server-side search logic to include the "Most Voted" status.
* [`client/app/(bots)/bots/components/Hero/SearchResults/Card/index.jsx`](diffhunk://#diff-0f7a4c833a8dbd324005031ac7a82b51caba08642ecbd70cddcbac7635c661b0R18-R19): Added `Tooltip` and `ImTrophy` components to display the "Most Voted" badge for bots. [[1]](diffhunk://#diff-0f7a4c833a8dbd324005031ac7a82b51caba08642ecbd70cddcbac7635c661b0R18-R19) [[2]](diffhunk://#diff-0f7a4c833a8dbd324005031ac7a82b51caba08642ecbd70cddcbac7635c661b0L155-R178)
* [`client/app/(servers)/servers/components/ServerCard/index.jsx`](diffhunk://#diff-5 …

feat: add most voted badge to bot/server cards based on monthly votes

---

docs/app/getting-started/page.mdx

This pull request includes updates to the mock data examples in the `docs/app/getting-started/page.mdx` file to include a new field, `server_count`, in addition to the existing `command_count`.
Updates to mock data examples:
* Added `server_count` field to the JavaScript mock data example using `axios` for API requests.
* Added `server_count` field to the Python mock data example using `requests` for API requests.
* Added `server_count` field to the curl command example for API requests.

fix(docs): add server_count field to mock data in getting-started page

---

server/src/bot/commands/general/ping.js
server/src/utils/getServerResponseTime.js

This pull request includes changes to the `ping` command to improve the way server response time is fetched by refactoring the code into a separate utility function.
* [`server/src/bot/commands/general/ping.js`](diffhunk://#diff-728556c0fd76f5c24e8a01cbeb110b953b7bea59a3774bb87f75d7be5308dc6bL1-R4): Removed the `axios` import and added an import for the new `getServerResponseTime` utility function.
* [`server/src/bot/commands/general/ping.js`](diffhunk://#diff-728556c0fd76f5c24e8a01cbeb110b953b7bea59a3774bb87f75d7be5308dc6bL17-R17): Modified the `ping` command to use the `getServerResponseTime` utility function instead of directly making the `axios` request.
* [`server/src/utils/getServerResponseTime.js`](diffhunk://#diff-1820e41d2b12f52f738597f81b2dabc9443ee69c9c823cb3de7fa5447747d83dR1-R …

fix(commands/ping): refactor to use getServerResponseTime utility

---

client/app/layout-content.js

This pull request updates the `RootLayoutContent` component to conditionally load the analytics script only in production environments. This helps prevent analytics from running during development or testing.

fix: conditionally render analytics script in production environment
