discordplace/discord.place

client/app/(servers)/servers/[id]/manage/content.js
client/app/(servers)/servers/manage/page.js
client/lib/request/servers/editServer.js
server/src/client.js
server/src/routes/servers/[id]/index.js
server/src/schemas/Server/index.js

Server owners will now be able to choose whether voice activity is collected by bot when adding or editing their servers.

Ability to disable voice activity

---

client/app/(bots)/bots/[id]/components/Tabs/Reviews.jsx
client/app/(servers)/servers/[id]/components/Tabs/Reviews.jsx
server/src/routes/bots/[id]/reviews.js
server/src/routes/servers/[id]/index.js
server/src/routes/servers/[id]/reviews.js
server/src/schemas/Bot/index.js

Prevent users from reviewing their own bots and servers.

Prevent self reviews

---

client/app/(bots)/bots/[id]/components/Tabs/Reviews.jsx
client/app/(bots)/bots/[id]/components/sections/RightSide/Actions.jsx
client/app/(bots)/bots/[id]/manage/content.js
client/app/(bots)/bots/manage/components/NewBot/index.jsx
client/app/(emojis)/emojis/components/EmojiPreview/index.jsx
client/app/(emojis)/emojis/components/PackagePreview/index.jsx
server/src/routes/bots/[id]/index.js
server/src/routes/bots/[id]/vote.js
server/src/schemas/Bot/index.js
server/src/schemas/Profile/index.js
server/src/utils/validations/bots/inviteUrl.js
server/src/utils/validations/bots/webhook.js
server/src/utils/validations/bots/webhookUrl.js

Added a webhook feature for bot votes
- Simplified some parts of the code ie. `v ? true : false`
- Added a new webhook feature

New Webhooks

---

server/src/bot/commands/admin.js
server/src/bot/commands/server.js
server/src/schemas/Server/LogChannel.js
server/src/schemas/Server/Vote/Reward.js
server/src/utils/servers/incrementVote.js
server/src/utils/servers/sendLog.js

I have added a system to reward people who vote a certain number of times with a role. I also made a system so that when someone votes or someone wins one of the rewards, it is sent as a message to the log channel.
- Firstly, I realized that we did not catch errors with .catch in the `dmChannel.send` function that we send DM to users, I fixed this situation.
- The schema files required to store the role rewards and the ID of the log channel in the database have been created.
- A function that allows us to easily send log messages to servers has been added to the utils.
- Added commands such as adding new rewards, viewing existing rewards, setting the log channel.
N/A

Vote rewards

---

server/src/bot/commands/stats.js

Reduced command cooldown to 1 minute, changed user count calculation, deleted 3 not needed db info

/stats: Reduce cooldown, fix user count, delete unnecessary db queries

---

client/app/page.js

It's not new anymore
Removed new badge from bots in homepage

Remove new badge from bots

---

client/app/(bots)/bots/components/Hero/Drawer/Sorting.jsx
client/app/(bots)/bots/components/Hero/PopularBots/Card/index.jsx
client/app/(bots)/bots/components/Hero/index.jsx
client/app/(dashboard)/components/Home/index.jsx

Lint rules in pull request #21 have been fixed.

fix (frontend): lint rules

---

client/app/(dashboard)/components/BotsQueue/Table/WaitingApproval.jsx
client/config.js

Invite Waiting bot to the test server with 0 perm
[List the changes made in this pull request.]
[Reference any related issues or tickets.]
[Include screenshots or gifs to visually demonstrate changes.]

Fix invite bot  to the test server with 0 perm on Dashboard page

---

client/app/legal/cookie-policy/page.js

Changed text from Content Policy to Cookie Policy

Fix Cookie Policy metadata

---

client/app/(account)/account/components/Content/Tabs/MyServers/NewServer/index.jsx
client/locales/az.json
client/locales/en.json
client/locales/tr.json
client/stores/language/index.js
server/config.yml
server/src/routes/auth/@me/data.js
server/src/routes/servers/[id]/index.js
server/src/utils/servers/requirementChecks.js

This pull request introduces a new feature that defines the requirements for listing a server. These requirements ensure that servers meet a certain standard before they can be listed, enhancing the quality and safety of the /servers page.
[Add server listing requirements to config.yml](https://github.com/discordplace/discord.place/commit/9853867536aa04338690b5a8340a544feecee865)
[Add requirementChecks util function](https://github.com/discordplace/discord.place/commit/1916f7df00be0907f0c1cbc62f4737fff3a2d025)
[Check requirements for servers](https://github.com/discordplace/discord.place/commit/2afd9eeaf0360fd78c188868355c6d777601f315)
[Add server listing requirements object to response in get auth data r…](https://github.com/discordplace/discord.place/commit/e08c3e4026eba2b81f46d9844f6791 …

Server listing requirements

---

client/app/(profiles)/profile/[slug]/components/sections/Graph/Likes.jsx
client/app/(profiles)/profile/[slug]/components/sections/Graph/Views.jsx
client/app/(servers)/servers/[id]/components/Tabs/Graph/MonthlyVotes.jsx

Fixed localizaton issues. Changed "noChange" localization key to "noChanges" in some components.
[Fix localization issues by changing localization key "noChange" to "n…](https://github.com/discordplace/discord.place/commit/e754a6c3b808f2385fddf639ed332e9b57399673)
N/A
N/A

Fix localization issues

---

client/app/(dashboard)/components/Home/index.jsx
client/app/(dashboard)/components/Queue/index.jsx
client/app/(dashboard)/components/Sidebar/BlockItem.jsx
client/app/(dashboard)/components/Sidebar/Icons/Collapse.jsx
client/app/(dashboard)/components/Sidebar/index.jsx
client/app/(dashboard)/components/Table/index.jsx
client/app/(dashboard)/dashboard/page.js
client/app/components/Logo/WithText.jsx
server/src/routes/dashboard.js

The Dashboard page now has a brand new look.
Old             |  New
:-------------------------:|:-------------------------:

Refactor Dashboard page

---

client/app/(dashboard)/components/Table/ColumnRenderer.jsx
client/app/(dashboard)/components/Table/index.jsx
client/app/(dashboard)/dashboard/page.js
client/package.json
client/pnpm-lock.yaml
client/stores/dashboard/index.js

Search items in the dashboard now a thing.

Add search functionality to Dashboard

---

server/src/bot/commands/admin/build.js

This pull request includes a change to the `server/src/bot/commands/admin/build.js` file to improve the build process logging.
* [`server/src/bot/commands/admin/build.js`](diffhunk://#diff-4d180947b4703530e5f05c2c8c585d00a18b2ee2233b25c41e5b12c0e8c257f9L18-R18): Removed the check for `stderr` and the corresponding error handling, simplifying the build command execution.

Refactor build command

---

client/app/components/Providers/Auth/index.jsx

This pull request includes a change to the `AuthProvider` component in the `client/app/components/Providers/Auth/index.jsx` file to integrate user identification with the Umami analytics tool.
Integration with Umami analytics:
* [`client/app/components/Providers/Auth/index.jsx`](diffhunk://#diff-17b0eabc5159a3dab114a3deb3ab880cfe6003989745805f7b43bdf8e5498ad5R21-R31): Added code to identify the user with Umami analytics by sending user metadata (`user_id` and `username`) if Umami is available in the `window` object.

Identify user with Umami on login

---

client/app/(account)/account/components/Content/Sidebar/BlockItem.jsx
client/app/(account)/account/components/Content/Sidebar/Icons/Collapse.jsx
client/app/(account)/account/components/Content/Sidebar/index.jsx
client/app/(account)/account/components/Content/Tabs/ActiveReminders/index.jsx
client/app/(account)/account/components/Content/Tabs/ActiveTimeouts/index.jsx
client/app/(account)/account/components/Content/Tabs/MyAccount/index.jsx
client/app/(account)/account/components/Content/Tabs/MyBots/index.jsx
client/app/(account)/account/components/Content/Tabs/MyEmojis/index.jsx
client/app/(account)/account/components/Content/Tabs/MyLinks/index.jsx
client/app/(account)/account/components/Content/Tabs/MyServers/index.jsx
client/app/(account)/account/components/Content/Tabs/MySounds/index.jsx
client/app/(account)/account/components/Content/Tabs/MyTemplates/index.jsx
client/app/(account)/account/components/Content/Tabs/MyThemes/index.jsx
client/app/(account)/account/components/Content/index.jsx
client/app/(dashboard)/components/Sidebar/index.jsx
client/locales/az.json
client/locales/en.json
client/locales/tr.json
server/src/bot/commands/reminder/index.js
server/src/routes/auth/@me/data.js

Account page has been redesigned. It is now more mobile-friendly.

Redesign account page

---

server/src/bot/commands/general/ping.js
server/src/bot/commands/reminder/index.js
server/src/routes/themes/[id]/index.js

This pull request includes several changes to import paths across multiple files to ensure consistency and correctness.
Path corrections:
* [`server/src/bot/commands/general/ping.js`](diffhunk://#diff-728556c0fd76f5c24e8a01cbeb110b953b7bea59a3774bb87f75d7be5308dc6bL4-R4): Updated the import path for `getLocalizedCommand` to use the correct relative path.
* [`server/src/bot/commands/reminder/index.js`](diffhunk://#diff-3237f40eed9197a51bcd3888b9a110167e97eece86fc533e05bdef019ac16b82L5-R5): Corrected the import path for `getLocalizedCommand` to match the updated directory structure.
* `server/src/routes/themes/[id]/index.js`: Fixed the import path for `getUserHashes` to ensure it points to the correct location.

Fix import paths for some utility functions

---

README.md
server/src/utils/createMongoBackup.js
server/src/utils/sendHeartbeat.js

This pull request includes several changes to add heartbeat functionality for monitoring the daily database backup process and updates to the documentation. The most important changes include adding a new environment variable for the heartbeat ID, updating the backup script to send heartbeats, and creating a new utility function to handle heartbeat requests.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R161): Added `HEARTBEAT_ID_DAILY_DATABASE_BACKUP` to the list of environment variables and explained its purpose for monitoring uptime using Better Stack Uptime. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R161) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 …

Add Better Stack Uptime heartbeat functionality

---

server/src/routes/auth/callback.js
server/src/utils/middlewares/checkAuthentication.js

This pull request includes minor changes to improve error logging in the authentication-related files. The changes involve standardizing the format of error messages by separating the static text and the error object.
Error logging improvements:
* [`server/src/routes/auth/callback.js`](diffhunk://#diff-fb7c3f82eaa1427d0898ff74625f44d0f135d38f681ece79288084cc62c2bbb7L109-R109): Modified the error logging statement to separate the static text and the error object.
* [`server/src/utils/middlewares/checkAuthentication.js`](diffhunk://#diff-745b04a6db998b79eb8dc39845ce995f5d0c40932eb4a451bbc15e0b03314889L37-R37): Updated the error logging statement to follow the same format, separating the static text and the error object.

refactor: error logging in authentication system

---

client/app/components/ImageFromHash/ServerBanner.jsx
client/app/components/ImageFromHash/ServerIcon.jsx
client/app/components/ImageFromHash/UserAvatar.jsx
client/app/components/ImageFromHash/UserBanner.jsx

This pull request includes updates to the `ImageFromHash` components to add unique keys to the `MotionImage` elements. This helps React identify which items have changed, are added, or are removed.
* [`client/app/components/ImageFromHash/ServerBanner.jsx`](diffhunk://#diff-252f8425604e526de160d578064106161301b4739505ce6d35a6d0d7ee8601bcR24): Added unique keys to `MotionImage` elements to improve React's reconciliation process. [[1]](diffhunk://#diff-252f8425604e526de160d578064106161301b4739505ce6d35a6d0d7ee8601bcR24) [[2]](diffhunk://#diff-252f8425604e526de160d578064106161301b4739505ce6d35a6d0d7ee8601bcR35)
* [`client/app/components/ImageFromHash/ServerIcon.jsx`](diffhunk://#diff-7ad5208bbc7eb45a010fb239c97a9d2482b45d4b7f76015e2d49815ef78e5e6eR24): Added unique keys to `MotionImage` …

feat: add unique keys for avatars, icons and banners

---

client/app/(bots)/bots/[id]/components/Tabs/Reviews.jsx
client/app/(servers)/servers/[id]/components/Tabs/Reviews.jsx
client/lib/request/bots/fetchReviews.js
client/lib/request/servers/fetchReviews.js
server/src/routes/bots/[id]/reviews/index.js
server/src/routes/servers/[id]/reviews/index.js

This pull request introduces significant changes to the review fetching and pagination functionality for both bots and servers. The changes include adding new API endpoints, updating the front-end components to handle asynchronous review fetching, and improving the user experience with loading states.

feat(reviews): implement actual pagination functionality

---

client/app/(account)/account/components/Content/Tabs/MyBots/index.jsx
client/config.js
client/lib/request/auth/getApplicationsEntitlementsScopeGranted.js
client/locales/az.json
client/locales/en.json
client/locales/tr.json
server/src/routes/auth/@me/applications-entitlements-scope-granted.js
server/src/routes/auth/@me/index.js
server/src/routes/auth/applicationsEntitlementsScope/callback.js
server/src/routes/auth/applicationsEntitlementsScope/index.js
server/src/routes/auth/callback.js
server/src/routes/bots/[id]/index.js
server/src/routes/scripts/closeWindow.js.js
server/src/schemas/User/index.js
server/src/utils/authCallback.js
server/src/utils/bots/isUserBotOwner.js
server/src/utils/getAccessToken.js

This pull request includes several changes to the `MyBots` component in the `client` directory and introduces new functionality for granting application entitlements scope. These changes collectively enhance the functionality of the `MyBots` component by allowing users to grant us necessary permissions.

feat(bots): add owner check when adding new bots

---

client/app/(account)/account/components/Content/Tabs/MyBots/NewBot/index.jsx
client/app/(bots)/bots/[id]/manage/components/EssentialInformation/index.jsx
client/app/components/Markdown/iframe.jsx
client/app/components/Markdown/index.jsx
client/lib/markdownComponents.jsx
client/locales/az.json
client/locales/en.json
client/locales/tr.json
client/package.json
client/pnpm-lock.yaml

This pull request introduces significant changes to the Markdown rendering and iframe handling in the application. The main updates include the addition of a custom iframe component with trust management, enhancements to the Markdown component, and updates to localization files to support new text strings.

feat(bots): allowing iframe in markdowns

---

server/src/utils/updateClientActivity.js

This pull request includes a small change to the `server/src/utils/updateClientActivity.js` file. The change adds a check to ensure that the `client` is ready before proceeding with the `updateClientActivity` function.

fix(client): ensure client is ready before updating activity

---

client/app/(bots)/bots/[id]/manage/components/Webhook/index.jsx
client/app/(bots)/bots/[id]/manage/content.js
client/app/(servers)/servers/[id]/manage/components/Webhook/index.jsx
client/app/(servers)/servers/[id]/manage/content.js
client/lib/request/bots/setWebhookSettings.js
client/lib/request/servers/setWebhookSettings.js
client/locales/az.json
client/locales/en.json
client/locales/tr.json
server/src/locales/en.json
server/src/locales/tr.json
server/src/routes/bots/[id]/index.js
server/src/routes/bots/[id]/webhook-settings.js
server/src/routes/servers/[id]/index.js
server/src/routes/servers/[id]/webhook-settings.js
server/src/schemas/Bot/index.js
server/src/schemas/Server/index.js
server/src/utils/bots/sendVoteWebhook.js
server/src/utils/servers/sendVoteWebhook.js

This pull request includes changes to add support for selecting and saving webhook language settings for both bots and servers for Discord webhooks.

feat(Webhooks): add language support for Discord webhooks

---

client/app/(bots)/bots/[id]/manage/components/Webhook/index.jsx
client/app/(servers)/servers/[id]/manage/components/Webhook/index.jsx
client/lib/request/bots/testWebhook.js
client/lib/request/clientRequest.js
client/lib/request/servers/testWebhook.js
client/locales/az.json
client/locales/en.json
client/locales/tr.json
client/package.json
client/pnpm-lock.yaml
docs/app/webhooks/page.mdx
package.json
pnpm-lock.yaml
server/src/client.js
server/src/routes/bots/[id]/test-webhook.js
server/src/routes/servers/[id]/test-webhook.js
server/src/utils/bots/incrementVote.js
server/src/utils/bots/sendVoteWebhook.js
server/src/utils/servers/incrementVote.js
server/src/utils/servers/sendVoteWebhook.js

This pull request introduces several enhancements and fixes across various components. The key changes include adding retry logic for webhooks.
Updated the webhook documentation to reflect the new retry logic for webhook requests.

feat(Webhooks): add retry logic

---

client/app/(sounds)/sounds/components/SoundPreview/Waveform.jsx
client/app/(sounds)/sounds/components/SoundPreview/index.jsx
client/locales/az.json
client/locales/en.json
client/locales/tr.json
client/stores/general/index.js

This pull request introduces several enhancements to the `SoundPreview` component and its related files, focusing on adding a loud sound warning feature and improving user experience with additional functionalities. The most important changes include adding a loud sound warning modal, updating the `Waveform` component to handle loud sounds, and enhancing the `SoundPreview` component with a clickable publisher link.
* [`client/app/(sounds)/sounds/components/SoundPreview/Waveform.jsx`](diffhunk://#diff-f1692949d4c705287d7e0b486f831b5c7ca7325814d3802d3601602061fc4b61R15-R18): Added a loud sound warning modal that triggers when a loud sound is played, with options to continue, cancel, or not show the warning again. Updated the `Waveform` component to check the maximum amplitude of the sound …

feat(sounds): add loud sound warning modal

---

server/src/routes/sounds/[id]/upload-to-guild.js

This pull request makes some small improvements to error handling and file data formatting in the `upload-to-guild` route. The main changes are to how sound file data is sent and how error messages are returned.

fix: correct sound file handling in upload-to-guild route

---

server/openapi.json
server/src/routes/openapi.json.js

This pull request introduces a new route handler for serving the OpenAPI specification as a JSON file. The handler sets the correct response header and sends the `openapi.json` file from the project root.

feat: add OpenAPI documentation
